blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/anupsharma555/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or start discussions about the activities system
  - name: 📚 View Documentation
    url: https://github.com/anupsharma555/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Read the development guide and technical documentation